name = "weatherynet"
compatibility_date = "2024-05-20"
main = "src/worker.js"
kv_namespaces = [
  { binding = "WEATHER_CACHE", id = "3b8966d31678435b9c11d997df962e84" }
]

[build]
command = "npm install && npm run build"

[observability]
enabled = true

[placement]
mode = "smart"
